name: Deployment pipeline

on:
  release:
    types: [published]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t cajsanu/rhythm-flow-backend:production .
          docker push cajsanu/rhythm-flow-backend:production
      - name: call Render.io hook to trigger the deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK }}